using UnityEngine;

public class BuildingDoor : Interactable
{
    [Header("Building Door Settings")]
    //[Tooltip("Name of the scene to load when entering this door")]
    //public string targetScene;

    [Header("Paired Door System")]
    [Tooltip("Unique ID for this door (should match the door in target scene)")]
    public string doorID;

    [Tooltip("Distance to spawn player from door")]
    public float spawnOffset = 2f;

    void Start()
    {
        //// Auto-create the transition action if not assigned
        //if (eventAction == null && !string.IsNullOrEmpty(targetScene))
        //{
        //    var transitionAction = ScriptableObject.CreateInstance<DoorEventAction>();
        //    transitionAction.targetSceneName = targetScene;
        //    transitionAction.pairedDoorID = doorID; // Use this door's ID as the paired door ID
        //    eventAction = transitionAction;
        //}
    }

   // Method to get the door ID
    public string GetDoorID()
    {
        return doorID;
    }

    // Method to get spawn position
    public Vector3 GetSpawnPosition()
    {
        return transform.position - transform.forward * spawnOffset;
    }

    // Optional: Visual debugging
    void OnDrawGizmos()
    {
        // Show where player will spawn (away from door)
        Gizmos.color = Color.green;
        Vector3 spawnPos = GetSpawnPosition();
        Gizmos.DrawWireSphere(spawnPos, 0.5f);

        // Show door forward direction
        Gizmos.color = Color.red;
        Gizmos.DrawRay(transform.position, transform.forward * 2f);

        // Show door ID in scene view
//#if UNITY_EDITOR
//        if (!string.IsNullOrEmpty(doorID))
//        {
//            UnityEditor.Handles.Label(transform.position + Vector3.up, $"Door ID: {doorID}");
//        }
//#endif
    }

//    [ContextMenu("Auto-Generate Door ID")]
//    private void AutoGenerateDoorID()
//    {
//        // Generate a door ID based on scene and target
//        string currentScene = gameObject.scene.name;
//        doorID = $"{currentScene}_to_{targetScene}";

//#if UNITY_EDITOR
//        UnityEditor.EditorUtility.SetDirty(this);
//#endif
//    }
}